name: phpinsights

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "pre", "pro"]

jobs:
  phpinsights:

    name: "Instant PHP quality checks from your console with phpinsights"
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run phpinsights
        run: ./vendor/bin/phpinsights --no-interaction --min-quality=50 --min-complexity=80 --min-architecture=70 --min-style=60 --disable-security-check
